FROM busybox:glibc
ADD https://github.com/F00cked/snell-server/raw/master/snell-2.0.1-bb-glibc/snell.tgz /
ADD https://github.com/F00cked/tzdata/raw/master/Alpine/zoneinfo/Asia/Shanghai /etc/localtime
# ENTRYPOINT ["init.sh"]